DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT NOT NULL,
    rouge TEXT NOT NULL,
    removed TEXT NOT NULL,
    reduction TEXT NOT NULL,
    speed TEXT NOT NULL
);